version: '3.1'
services:

  db:
    image: postgres:latest
    restart: always
    container_name: spybot-db
    volumes:
      - db_data:/home/lib/postgresql
    env_file:
      - .env
    ports:
      - 5432:5432
  
  backend:
    build:
      context: .
    restart: always
    container_name: spybot-back
    command: ['/spybot_sb/docker/backend.sh']
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db_data: